version: '3'
networks:
  agendared2:
    ipam:
      config:
        - subnet: 182.28.0.0/16
          gateway: 182.28.0.1
services:
  db:
    image: bitnami/mongodb:latest
    container_name: mongo-agenda
    ports:
      - "27017:27017"
    networks:
      agendared2:
        ipv4_address: 182.28.0.11
    expose:
      - 27017
  app-agenda:
    image: angelwoo/aw_agenda:7
    container_name: agenda_app
    networks:
      agendared2:
        ipv4_address: 182.28.0.12
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - db